######################################################################
##
## Filename: tb.fdo
## Created on: Thu Mar 09 16:55:25 Paris, Madrid 2023
##
##  Auto generated by Project Navigator for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the project directory and will not be removed on
##  subsequent simulation flows run from Project Navigator.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#
# Create work library
#
vlib work
#
# Compile sources
#
vcom -explicit  -93 "../Tristate/Tristate.vhd"
vcom -explicit  -93 "../Somateur/Somateur.vhd"
vcom -explicit  -93 "../RegistreNbits/RegistreNbits.vhd"
vcom -explicit  -93 "../DivHorloge/DivHorloge.vhd"
vcom -explicit  -93 "../CompteurNbits/CompteurNbits.vhd"
vcom -explicit  -93 "../Coefficient/Coefficient.vhd"
vcom -explicit  -93 "Biblio/Biblio.vhd"
vcom -explicit  -93 "CNA_Nbits.vhd"
vcom -explicit  -93 "tb.vhd"
#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps  -lib work work.tb
#
# Source the wave do file
#
#do {tb_wave.fdo}
do wave.do
#
# Set the window types
#
view wave
view structure
view signals
#
# Source the user do file
#
do {tb.udo}
#
# Run simulation for this time
#
run 500 us
#
# End
#
