######################################################################
##
## Filename: tb.udo
## Created on: Thu Mar 09 16:55:25 Paris, Madrid 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
