######################################################################
##
## Filename: tb.udo
## Created on: Mon Mar 06 09:57:02 Paris, Madrid 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
